version: '3'
networks:
  traefik:
    external:
      name: plataforma_network
services:
  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - "1080:80"
      - "25:25"
    networks:
      - traefik
    labels:
      - "traefik.backend=maildev"
      - "traefik.docker.network=plataforma_network"
      - "traefik.maildev.frontend.rule=PathPrefixStrip: /maildev"
      - "traefik.port=80"
